name: Build DodyClicker Windows
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
        shell: powershell
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico --add-data "icon.ico;." --name "DodyClicker15" DodyClicker15.py
        shell: powershell
      - name: Release Executable
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: dist/DodyClicker15.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}